import { moveMessagePortToContext } from "worker_threads";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_FETCHING = "REGISTER_FETCHING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FETCHING = "LOGIN_FETCHING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const ACTIVE_PROBLEM_REQUEST = "ACTIVE_PROBLEM_REQUEST";
export const ACTIVE_PROBLEM_FETCHING = "ACTIVE_PROBLEM_FETCHING";
export const ACTIVE_PROBLEM_SUCCESS = "ACTIVE_PROBLEM_SUCCESS";
export const ACTIVE_PROBLEM_FAILED = "ACTIVE_PROBLEM_FAILED";

export const PROBLEMID_REQUEST = "PROBLEMID_REQUEST";
export const PROBLEMID_FETCHING = "PROBLEMID_FETCHING";
export const PROBLEMID_SUCCESS = "PROBLEMID_SUCCESS";
export const PROBLEMID_FAILED = "PROBLEMID_FAILED";

export const SUBMISSIONID_REQUEST = "SUBMISSIONID_REQUEST";
export const SUBMISSIONID_FETCHING = "SUBMISSIONID_FETCHING";
export const SUBMISSIONID_SUCCESS = "SUBMISSIONID_SUCCESS";
export const SUBMISSIONID_FAILED = "SUBMISSIONID_FAILED";

export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_FETCHING = "PROFILE_FETCHING";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILED = "PROFILE_FAILED";

export const SUBMIT_REQUEST = "SUBMIT_REQUEST";
export const SUBMIT_FETCHING = "SUBMIT_FETCHING";
export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS";
export const SUBMIT_FAILED = "SUBMIT_FAILED";

export const TPROBLEM_REQUEST = "TPROBLEM_REQUEST";
export const TPROBLEM_FETCHING = "TPROBLEM_FETCHING";
export const TPROBLEM_SUCCESS = "TPROBLEM_SUCCESS";
export const TPROBLEM_FAILED = "TPROBLEM_FAILED";
