import { moveMessagePortToContext } from "worker_threads";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_FETCHING = "REGISTER_FETCHING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FETCHING = "LOGIN_FETCHING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const ACTIVE_PROBLEM_REQUEST = "ACTIVE_PROBLEM_REQUEST";
export const ACTIVE_PROBLEM_FETCHING = "ACTIVE_PROBLEM_FETCHING";
export const ACTIVE_PROBLEM_SUCCESS = "ACTIVE_PROBLEM_SUCCESS";
export const ACTIVE_PROBLEM_FAILED = "ACTIVE_PROBLEM_FAILED";

export const PROBLEMID_REQUEST = "PROBLEMID_REQUEST";
export const PROBLEMID_FETCHING = "PROBLEMID_FETCHING";
export const PROBLEMID_SUCCESS = "PROBLEMID_SUCCESS";
export const PROBLEMID_FAILED = "PROBLEMID_FAILED";

export const SUBMISSIONID_REQUEST = "SUBMISSIONID_REQUEST";
export const SUBMISSIONID_FETCHING = "SUBMISSIONID_FETCHING";
export const SUBMISSIONID_SUCCESS = "SUBMISSIONID_SUCCESS";
export const SUBMISSIONID_FAILED = "SUBMISSIONID_FAILED";

export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_FETCHING = "PROFILE_FETCHING";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILED = "PROFILE_FAILED";

export const SUBMIT_REQUEST = "SUBMIT_REQUEST";
export const SUBMIT_FETCHING = "SUBMIT_FETCHING";
export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS";
export const SUBMIT_FAILED = "SUBMIT_FAILED";

export const TPROBLEM_REQUEST = "TPROBLEM_REQUEST";
export const TPROBLEM_FETCHING = "TPROBLEM_FETCHING";
export const TPROBLEM_SUCCESS = "TPROBLEM_SUCCESS";
export const TPROBLEM_FAILED = "TPROBLEM_FAILED";

export const TESTCASE_REQUEST = "TESTCASE_REQUEST";
export const TESTCASE_FETCHING = "TESTCASE_FETCHING";
export const TESTCASE_SUCCESS = "TESTCASE_SUCCESS";
export const TESTCASE_FAILED = "TESTCASE_FAILED";

export const CREATE_PROBLEM_REQUEST = "CREATE_PROBLEM_REQUEST";
export const CREATE_PROBLEM_FETCHING = "CREATE_PROBLEM_FETCHING";
export const CREATE_PROBLEM_SUCCESS = "CREATE_PROBLEM_SUCCESS";
export const CREATE_PROBLEM_FAILED = "CREATE_PROBLEM_FAILED";

export const TPROBLEMID_REQUEST = "TPROBLEMID_REQUEST";
export const TPROBLEMID_FETCHING = "TPROBLEMID_FETCHING";
export const TPROBLEMID_SUCCESS = "TPROBLEMID_SUCCESS";
export const TPROBLEMID_FAILED = "TPROBLEMID_FAILED";

export const UPLOAD_STUDENT_REQUEST = "UPLOAD_STUDENT_REQUEST";
export const UPLOAD_STUDENT_FETCHING = "UPLOAD_STUDENT_FETCHING";
export const UPLOAD_STUDENT_SUCCESS = "UPLOAD_STUDENT_SUCCESS";
export const UPLOAD_STUDENT_FAILED = "UPLOAD_STUDENT_FAILED";

export const STUDENT_REQUEST = "STUDENT_REQUEST";
export const STUDENT_FETCHING = "STUDENT_FETCHING";
export const STUDENT_SUCCESS = "STUDENT_SUCCESS";
export const STUDENT_FAILED = "STUDENT_FAILED";

export const SWITCHID_REQUEST = "SWITCHID_REQUEST";
export const SWITCHID_FETCHING = "SWITCHID_FETCHING";
export const SWITCHID_SUCCESS = "SWITCHID_SUCCESS";
export const SWITCHID_FAILED = "SWITCHID_FAILED";
